---
- hosts: ios
  tasks:
  - name: "Configure throughput level"
    ios_config:
      provider: "{{cli}}"
      lines:
        - "platform hardware throughput level MB 1000"
  - name: "Save Configuration"
    ios_command:
      provider: "{{cli}}"
      commands: wr